apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-7pop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-7pop
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-7pop
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-7pop
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-7pop
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-myyq-tenant/rhtap-demo-app/hacbs-test-project-7pop@sha256:cf70321cf5626d1fee7fa0a613f79dfe24922066e00e8db14778311427e170c0
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
